stages:
    - build
    - unitTests
    - test

variables:
  PROJECT_NAME: "List"
  BINARY_PATH: "bin"
  TEST_FILES_PATH: "/home/gitlab-runner/ADS/List"

before_script:
  - /opt/QtCreator/bin/qbs-setup-toolchains --detect

linux:
  tags:
    - seminars
  stage: build
  
  script: 
    - /opt/QtCreator/bin/qbs -f $PROJECT_NAME.qbs profile:gcc qbs.installRoot:. config:linux qbs.defaultBuildVariant:debug

  cache:
    paths:
      - $BINARY_PATH/$PROJECT_NAME
      - $BINARY_PATH/tests
    
  artifacts:
    paths:
      - $BINARY_PATH/$PROJECT_NAME
      - $BINARY_PATH/tests
    when: always

win:
  tags:
    - seminars

  stage: build
  allow_failure: true

  script:
    - /opt/QtCreator/bin/qbs -f $PROJECT_NAME.qbs profile:i686-w64-mingw32.static qbs.installRoot:. config:win qbs.defaultBuildVariant:debug

  artifacts:
    paths:
      - $BINARY_PATH/$PROJECT_NAME.exe
      - $BINARY_PATH/tests.exe

unitTesting:
  tags:
    - seminars
  stage: unitTests
  allow_failure: true
  
  script:
    - bin/tests > unitTestOutput.txt
    - if [[ `cat unitTestOutput.txt` =~ ", 0 failures" ]];then exit 0;else exit 1;fi
    
  artifacts:
    paths:
      - unitTestOutput.txt
    when: always
    
test1:
  tags:
    - seminars
  stage: test
  
  script: 
    - valgrind --log-file=valgrindOutput1.txt $BINARY_PATH/$PROJECT_NAME < $TEST_FILES_PATH/input1.txt > output1.txt
    - diff output1.txt $TEST_FILES_PATH/output1.txt > diffOutput1.diff
    - if [[ `cat valgrindOutput1.txt` =~ "no leaks are possible" ]];then exit 0;else exit 1;fi
    
  artifacts:
    paths:
      - output1.txt
      - diffOutput1.diff
      - valgrindOutput1.txt
    when: always
    
test2:
  tags:
    - seminars
  stage: test
  
  script: 
    - valgrind --log-file=valgrindOutput2.txt $BINARY_PATH/$PROJECT_NAME < $TEST_FILES_PATH/input2.txt > output2.txt
    - diff output2.txt $TEST_FILES_PATH/output2.txt > diffOutput2.diff
    - if [[ `cat valgrindOutput2.txt` =~ "no leaks are possible" ]];then exit 0;else exit 1;fi
    
  artifacts:
    paths:
      - output2.txt
      - diffOutput2.diff
      - valgrindOutput2.txt
    when: always
    
test3:
  tags:
    - seminars
  stage: test
  
  script: 
    - valgrind --log-file=valgrindOutput3.txt $BINARY_PATH/$PROJECT_NAME < $TEST_FILES_PATH/input3.txt > output3.txt
    - diff output3.txt $TEST_FILES_PATH/output3.txt > diffOutput3.diff
    - if [[ `cat valgrindOutput3.txt` =~ "no leaks are possible" ]];then exit 0;else exit 1;fi
    
  artifacts:
    paths:
      - output3.txt
      - diffOutput3.diff
      - valgrindOutput3.txt
    when: always

    test4:
  tags:
    - seminars
  stage: test
  
  script: 
    - valgrind --log-file=valgrindOutput4.txt $BINARY_PATH/$PROJECT_NAME < $TEST_FILES_PATH/input4.txt > output4.txt
    - diff output4.txt $TEST_FILES_PATH/output4.txt > diffOutput4.diff
    - if [[ `cat valgrindOutput4.txt` =~ "no leaks are possible" ]];then exit 0;else exit 1;fi
    
  artifacts:
    paths:
      - output4.txt
      - diffOutput4.diff
      - valgrindOutput4.txt
    when: always
    
test4:
  tags:
    - seminars
  stage: test
  
  script: 
    - valgrind --log-file=valgrindOutput4.txt $BINARY_PATH/$PROJECT_NAME < $TEST_FILES_PATH/input4.txt > output4.txt
    - diff output4.txt $TEST_FILES_PATH/output4.txt > diffOutput4.diff
    - if [[ `cat valgrindOutput4.txt` =~ "no leaks are possible" ]];then exit 0;else exit 1;fi
    
  artifacts:
    paths:
      - output5.txt
      - diffOutput5.diff
      - valgrindOutput5.txt
    when: always